import { YoutubeTranscript } from 'youtube-transcript';

export async function getTranscript(url: string): Promise<string> {
  try {
    console.log("Extracting video ID from URL:", url);
    const videoId = extractVideoId(url);
    if (!videoId) {
      throw new Error("Invalid YouTube URL. Please ensure you've entered a valid YouTube video URL.");
    }
    console.log("Extracted video ID:", videoId);

    // Try different transcript fetch strategies
    try {
      // First attempt: Try with default options
      const transcript = await YoutubeTranscript.fetchTranscript(videoId);
      return processTranscript(transcript);
    } catch (error: any) {
      console.log("First attempt failed, trying with alternative options...");

      // Second attempt: Try with lang=en parameter
      try {
        const transcript = await YoutubeTranscript.fetchTranscript(videoId, {
          lang: 'en'
        });
        return processTranscript(transcript);
      } catch (secondError: any) {
        console.log("Second attempt failed, trying auto-generated captions...");

        // Third attempt: Try with auto-generated captions
        try {
          const transcript = await YoutubeTranscript.fetchTranscript(videoId, {
            lang: 'en',
            useAutoGenerated: true
          });
          return processTranscript(transcript);
        } catch (thirdError: any) {
          // If all attempts fail, throw a comprehensive error
          throw new Error(
            "Could not access video transcript. This could be because:\n" +
            "1. The video has disabled captions\n" +
            "2. The video is private or age-restricted\n" +
            "3. Auto-generated captions are not available\n\n" +
            "Please try a different video that has captions enabled."
          );
        }
      }
    }
  } catch (error: any) {
    console.error("Transcript fetch error:", error);
    throw error;
  }
}

function processTranscript(transcript: any[]): string {
  if (!transcript || transcript.length === 0) {
    throw new Error("No transcript content available for this video");
  }
  console.log(`Fetched transcript with ${transcript.length} segments`);
  const fullTranscript = transcript.map(item => item.text).join(' ');
  console.log(`Total transcript length: ${fullTranscript.length} characters`);
  return fullTranscript;
}

function extractVideoId(url: string): string | null {
  try {
    const urlObj = new URL(url);
    let videoId: string | null = null;

    // Handle youtube.com URLs
    if (urlObj.hostname.includes('youtube.com')) {
      // Handle standard video URLs
      videoId = urlObj.searchParams.get('v');
      if (videoId) {
        console.log("Found video ID in query params:", videoId);
        return videoId;
      }

      // Handle shorts URLs
      const pathSegments = urlObj.pathname.split('/');
      const shortsIndex = pathSegments.indexOf('shorts');
      if (shortsIndex !== -1 && pathSegments[shortsIndex + 1]) {
        videoId = pathSegments[shortsIndex + 1].split('?')[0]; // Remove any query parameters
        console.log("Found video ID in shorts URL:", videoId);
        return videoId;
      }
    }

    // Handle youtu.be URLs
    if (urlObj.hostname === 'youtu.be') {
      videoId = urlObj.pathname.substring(1).split('?')[0]; // Remove any query parameters
      if (videoId) {
        console.log("Found video ID in youtu.be URL:", videoId);
        return videoId;
      }
    }

    console.log("No video ID found in URL");
    return null;
  } catch (error) {
    console.error("Error extracting video ID:", error);
    return null;
  }
}